"""Product specs for the local demo store catalogue (MOCK DATA ONLY).

``BASE_SPECS`` covers the themed region x discipline products (product type and
asset kind derived from the discipline); ``SHOWCASE_SPECS`` adds explicit
products across every canonical product type and asset kind (standardised
reports, summaries, satellite imagery, geospatial overlays, database extracts,
SIGINT datasets, product bundles and fused outputs).
"""

from coeus.domain.access import ProductStatus

_P = ProductStatus.PUBLISHED
_D = ProductStatus.DRAFT

# (acg_code, title, classification, status, (start, end))
BASE_SPECS: tuple[tuple[str, str, int, ProductStatus, tuple[str, str]], ...] = (
    (
        "ACG-EU-CYBER",
        "Eastern Europe Ransomware Infrastructure Review",
        3,
        _P,
        ("2026-05-01", "2026-06-30"),
    ),
    ("ACG-EU-CYBER", "Grid Control Intrusion Set Assessment", 3, _P, ("2026-04-01", "2026-05-31")),
    (
        "ACG-EU-HUMINT",
        "Border Facilitation Network Assessment",
        3,
        _P,
        ("2026-03-15", "2026-05-15"),
    ),
    (
        "ACG-EU-SIGINT",
        "Baltic Emitter Pattern-of-Life Summary",
        3,
        _P,
        ("2026-05-10", "2026-06-20"),
    ),
    ("ACG-EU-GEOINT", "Kaliningrad Corridor Movement Imagery", 2, _P, ("2026-06-01", "2026-06-25")),
    (
        "ACG-EU-OSINT",
        "Eastern Europe Sentiment and Mobilisation Digest",
        1,
        _P,
        ("2026-06-01", "2026-06-30"),
    ),
    (
        "ACG-AF-HUMINT",
        "Sahel Militia Leadership Network Brief",
        3,
        _P,
        ("2026-04-10", "2026-06-01"),
    ),
    ("ACG-AF-OSINT", "West Africa Coup Indicators Digest", 2, _P, ("2026-05-20", "2026-06-28")),
    ("ACG-AF-GEOINT", "Gulf of Guinea Port Activity Imagery", 2, _P, ("2026-05-01", "2026-06-15")),
    (
        "ACG-ME-HUMINT",
        "Eastern Mediterranean Smuggling Route Assessment",
        3,
        _P,
        ("2026-03-01", "2026-05-01"),
    ),
    (
        "ACG-ME-SIGINT",
        "Levant Coastal Emitter Collection Summary",
        3,
        _P,
        ("2026-05-05", "2026-06-18"),
    ),
    (
        "ACG-ME-OSINT",
        "Regional Escalation Media Monitoring Digest",
        1,
        _P,
        ("2026-06-05", "2026-06-30"),
    ),
    (
        "ACG-AP-GEOINT",
        "South China Sea Reef Construction Imagery",
        3,
        _P,
        ("2026-04-15", "2026-06-10"),
    ),
    ("ACG-AP-SIGINT", "Western Pacific Naval Emitter Summary", 3, _P, ("2026-05-12", "2026-06-22")),
    (
        "ACG-AP-CYBER",
        "Regional State-Sponsored Intrusion Set Review",
        3,
        _P,
        ("2026-04-01", "2026-06-01"),
    ),
    (
        "ACG-AP-OSINT",
        "Asia-Pacific Shipping Disruption Digest",
        1,
        _P,
        ("2026-06-01", "2026-06-28"),
    ),
    (
        "ACG-NA-CYBER",
        "Critical Infrastructure Phishing Campaign Review",
        2,
        _P,
        ("2026-05-01", "2026-06-20"),
    ),
    ("ACG-NA-OSINT", "North America Supply Chain Risk Digest", 1, _P, ("2026-06-01", "2026-06-30")),
    (
        "ACG-SA-HUMINT",
        "Andean Trafficking Facilitation Assessment",
        3,
        _P,
        ("2026-03-20", "2026-05-20"),
    ),
    (
        "ACG-SA-OSINT",
        "South America Instability Indicators Digest",
        1,
        _P,
        ("2026-05-25", "2026-06-27"),
    ),
    (
        "ACG-AR-GEOINT",
        "Arctic Sea Route Ice and Traffic Imagery",
        2,
        _P,
        ("2026-05-01", "2026-06-15"),
    ),
    ("ACG-AR-SIGINT", "High North Emitter Activity Summary", 3, _P, ("2026-05-10", "2026-06-20")),
    ("ACG-AR-OSINT", "Arctic Council Posture Media Digest", 1, _P, ("2026-06-01", "2026-06-29")),
    ("ACG-MAR-GEOINT", "North Atlantic Convoy Route Imagery", 2, _P, ("2026-05-15", "2026-06-25")),
    (
        "ACG-MAR-SIGINT",
        "North Atlantic Submarine Transit Emitter Summary",
        3,
        _P,
        ("2026-05-01", "2026-06-18"),
    ),
    (
        "ACG-MAR-OSINT",
        "Maritime Shipping and Insurance Risk Digest",
        1,
        _P,
        ("2026-06-02", "2026-06-30"),
    ),
    (
        "ACG-EU-CYBER",
        "Draft: Emerging Wiper Malware Assessment",
        3,
        _D,
        ("2026-06-20", "2026-06-30"),
    ),
    (
        "ACG-MAR-GEOINT",
        "Draft: Harbour Sentinel Coverage Imagery",
        2,
        _D,
        ("2026-06-18", "2026-06-28"),
    ),
)

# (acg_code, title, product_type, asset_kind, classification, status, period, tags)
SHOWCASE_SPECS: tuple[
    tuple[str, str, str, str, int, ProductStatus, tuple[str, str], tuple[str, ...]], ...
] = (
    (
        "ACG-EU-OSINT",
        "Standardised Intelligence Assessment: Eastern Flank",
        "assessment_report",
        "pdf",
        2,
        _P,
        ("2026-06-01", "2026-06-30"),
        ("standardised", "nato-format", "eastern-flank"),
    ),
    (
        "ACG-EU-OSINT",
        "Daily Intelligence Summary (DISUM) 2026-179",
        "intelligence_summary",
        "pdf",
        1,
        _P,
        ("2026-06-28", "2026-06-28"),
        ("disum", "daily", "current-intelligence"),
    ),
    (
        "ACG-ME-HUMINT",
        "Counter-UAS Threat Assessment",
        "assessment_report",
        "pdf",
        3,
        _P,
        ("2026-05-01", "2026-06-20"),
        ("counter-uas", "drone", "force-protection"),
    ),
    (
        "ACG-AP-OSINT",
        "Fused All-Source Assessment: South China Sea",
        "finished_output",
        "pdf",
        3,
        _P,
        ("2026-04-01", "2026-06-25"),
        ("all-source", "fused", "maritime"),
    ),
    (
        "ACG-AR-GEOINT",
        "Severomorsk Naval Base Satellite Imagery",
        "satellite_imagery_product",
        "image",
        3,
        _P,
        ("2026-06-10", "2026-06-12"),
        ("naval-base", "satellite", "order-of-battle"),
    ),
    (
        "ACG-EU-GEOINT",
        "Kaliningrad SAM Site Imagery Pack",
        "satellite_imagery_product",
        "image",
        3,
        _P,
        ("2026-06-05", "2026-06-15"),
        ("air-defence", "sam", "imagery"),
    ),
    (
        "ACG-EU-GEOINT",
        "Baltic Air Defence Coverage Overlay",
        "geographic_product",
        "geojson",
        3,
        _P,
        ("2026-05-20", "2026-06-20"),
        ("air-defence", "coverage", "overlay"),
    ),
    (
        "ACG-AF-GEOINT",
        "Sahel Threat Activity Heatmap Layer",
        "geographic_product",
        "geojson",
        2,
        _P,
        ("2026-05-01", "2026-06-15"),
        ("heatmap", "threat", "overlay"),
    ),
    (
        "ACG-MAR-OSINT",
        "North Atlantic Vessel Movement Database Extract",
        "database_extract",
        "csv",
        2,
        _P,
        ("2026-06-01", "2026-06-30"),
        ("ais", "vessel-tracking", "dataset"),
    ),
    (
        "ACG-EU-CYBER",
        "Threat Actor Infrastructure Indicator Extract",
        "database_extract",
        "csv",
        3,
        _P,
        ("2026-05-15", "2026-06-28"),
        ("iocs", "infrastructure", "dataset"),
    ),
    (
        "ACG-AR-GEOINT",
        "Arctic Route Intelligence Bundle",
        "product_bundle",
        "bundle",
        2,
        _P,
        ("2026-05-01", "2026-06-20"),
        ("bundle", "arctic", "multi-source"),
    ),
    (
        "ACG-ME-OSINT",
        "Levant Situation Awareness Pack",
        "product_bundle",
        "bundle",
        2,
        _P,
        ("2026-06-01", "2026-06-29"),
        ("bundle", "situation", "levant"),
    ),
    (
        "ACG-EU-SIGINT",
        "Baltic ELINT Parametric Dataset",
        "sigint_mock",
        "sigint",
        3,
        _P,
        ("2026-05-10", "2026-06-22"),
        ("elint", "parametric", "dataset"),
    ),
    (
        "ACG-AP-GEOINT",
        "Draft: Spratly Islands Change-Detection Imagery",
        "satellite_imagery_product",
        "image",
        3,
        _D,
        ("2026-06-20", "2026-06-27"),
        ("change-detection", "imagery", "spratly"),
    ),
)
