"""Collection-management rows for the synthetic operational task manifest."""

from coeus.domain.enums import TicketState
from coeus.domain.team_task_ownership import WorkflowLeg
from coeus.domain.work_packages import CanonicalWorkPackageState
from coeus.repositories.synthetic_task_manifest import SyntheticTaskSpec, _closed, _task


def synthetic_cm_task_specs() -> tuple[SyntheticTaskSpec, ...]:
    cm = WorkflowLeg.CM_COLLECTION
    return (
        _task(
            "open-1",
            "EXR-2013",
            "Open-source collection requirement",
            "cm_open",
            "collection.team@example.test",
            "user@example.test",
            cm,
            TicketState.ANALYST_ASSIGNMENT,
            None,
            "Routine",
            12,
        ),
        _task(
            "open-2",
            "EXR-2014",
            "Media monitoring collection plan",
            "cm_open",
            "collection.team@example.test",
            "customer.3@example.test",
            cm,
            TicketState.ANALYST_IN_PROGRESS,
            True,
            "High",
            5,
        ),
        _task(
            "open-3",
            "EXR-2015",
            "Source validation collection task",
            "cm_open",
            "collection.team@example.test",
            "customer.4@example.test",
            cm,
            TicketState.JIOC_INTERVENTION_HOLD,
            True,
            "Routine",
            8,
            CanonicalWorkPackageState.BLOCKED,
        ),
        _task(
            "geo-1",
            "EXR-2016",
            "Geospatial coverage requirement",
            "cm_geo",
            "cm.lead.2@example.test",
            "colleague@example.test",
            cm,
            TicketState.ANALYST_ASSIGNMENT,
            None,
            "Routine",
            15,
        ),
        _task(
            "geo-2",
            "EXR-2017",
            "Synthetic imagery collection plan",
            "cm_geo",
            "cm.lead.2@example.test",
            "customer.5@example.test",
            cm,
            TicketState.ANALYST_IN_PROGRESS,
            True,
            "Urgent",
            1,
        ),
        _task(
            "geo-3",
            "EXR-2018",
            "Coverage gap review",
            "cm_geo",
            "cm.lead.2@example.test",
            "customer.6@example.test",
            cm,
            TicketState.MANAGER_APPROVAL,
            True,
            "High",
            3,
        ),
        _task(
            "req-1",
            "EXR-2019",
            "Collection requirement deconfliction",
            "cm_requirements",
            "cm.lead.3@example.test",
            "user@example.test",
            cm,
            TicketState.ANALYST_ASSIGNMENT,
            None,
            "Routine",
            11,
        ),
        _task(
            "req-2",
            "EXR-2020",
            "Multi-source collection coordination",
            "cm_requirements",
            "cm.lead.3@example.test",
            "customer.3@example.test",
            cm,
            TicketState.ANALYST_IN_PROGRESS,
            True,
            "High",
            4,
        ),
        _task(
            "req-3",
            "EXR-2021",
            "Analysed collection handover",
            "cm_requirements",
            "cm.lead.3@example.test",
            "customer.4@example.test",
            WorkflowLeg.CM_ANALYSIS,
            TicketState.MANAGER_APPROVAL,
            True,
            "Routine",
            3,
        ),
        _closed(
            "closed-geo",
            "EXR-2023",
            "Completed geospatial collection brief",
            "cm_geo",
            "cm.lead.2@example.test",
            True,
            cm,
        ),
        _closed(
            "closed-req",
            "EXR-2024",
            "Completed requirements coordination",
            "cm_requirements",
            "cm.lead.3@example.test",
            True,
            cm,
        ),
    )
