import type { RfiSearchResults } from "../../lib/api-client/rfi-search";
import type { Ticket } from "../../lib/api-client/tickets";

export const requestTicket: Ticket = {
  id: "ticket-1",
  reference: "TCK-0001",
  requesterUserId: "preview-user",
  state: "DRAFT_INTAKE",
  intake: {
    title: "Regional Brief",
    description: "Assess activity.",
    operationalQuestion: "What changed?",
    areaOrRegion: "Baltic ports",
    timePeriodStart: "next week",
    timePeriodEnd: null,
    priority: "routine",
    deadline: null,
    requiredOutputFormat: "Briefing note",
    knownContext: null,
    restrictionsOrCaveats: null,
    customerSuccessCriteria: "Support watch teams.",
    suggestedAcgContext: null,
    requestingUnit: "Carrier Strike Group Atlas",
    intelligenceDisciplines: "IMINT",
    supportedOperation: null,
    urgencyJustification: null,
    missingInformation: [],
    confidence: 1,
  },
  intakeChecklist: [
    { key: "description", label: "What you need", value: "Assess activity.", satisfied: true },
    {
      key: "operational_question",
      label: "Question to answer",
      value: "What changed?",
      satisfied: true,
    },
    { key: "area_or_region", label: "Area or region", value: "Baltic ports", satisfied: true },
    { key: "time_period", label: "Time period", value: "next week", satisfied: true },
    { key: "priority", label: "Priority", value: "routine", satisfied: true },
    {
      key: "requesting_unit",
      label: "Requesting unit",
      value: "Carrier Strike Group Atlas",
      satisfied: true,
    },
    { key: "intelligence_disciplines", label: "Disciplines", value: "IMINT", satisfied: true },
    {
      key: "required_output_format",
      label: "Output format",
      value: "Briefing note",
      satisfied: true,
    },
    {
      key: "customer_success_criteria",
      label: "Success criteria",
      value: "Support watch teams.",
      satisfied: true,
    },
    { key: "title", label: "Title", value: "Regional Brief", satisfied: true },
  ],
  conversationStatus: "open",
  collectDisposition: null,
  isReadyForSubmission: true,
  visibleProductMatches: [],
  releasedProductIds: [],
  collaborators: [],
  messages: [],
  attachments: [],
  agentRuns: [],
  timeline: [],
  createdAt: "2026-07-05T00:00:00Z",
  updatedAt: "2026-07-05T00:00:00Z",
};

export const rfiResultsFixture: RfiSearchResults = {
  ticketId: "ticket-1",
  ticketState: "RFI_MATCH_OFFERED",
  retrievalMode: "hybrid",
  degradedReason: null,
  metrics: {
    runId: "run-1",
    query: "Regional Stability Brief Baltic ports assessment report",
    candidateCount: 1,
    offeredCount: 1,
    rejectedCount: 0,
    acceptedProductId: null,
    createdAt: "2026-07-05T00:01:00Z",
    retrievalMode: "hybrid",
    degradedReason: null,
  },
  offers: [
    {
      productId: "product-1",
      title: "Regional Stability Brief",
      summary: "MOCK DATA ONLY assessment summary.",
      productType: "assessment_report",
      matchScore: 0.86,
      matchReasons: ["full-text:regional", "metadata:region"],
      classificationLevel: 2,
      releasability: ["MOCK"],
      region: "Baltic ports",
      timePeriodStart: null,
      timePeriodEnd: null,
      assetTypes: ["pdf"],
      offerableToUser: true,
      status: "offered",
      rejectionReason: null,
      passages: [
        {
          citation: "Regional brief.pdf, page 2",
          chunkId: "chunk-1",
          assetId: "asset-1",
          assetName: "Regional brief.pdf",
          pageNumber: 2,
          excerpt: "Synthetic reporting describes activity around the assessed ports.",
        },
      ],
    },
  ],
};
