import type { RfiSearchResults } from "../../lib/api-client/rfi-search";
import type { Ticket } from "../../lib/api-client/tickets";

export const requestTicket: Ticket = {
  id: "ticket-1",
  reference: "TCK-0001",
  requesterUserId: "preview-user",
  state: "DRAFT_INTAKE",
  intake: {
    title: "Regional Brief",
    description: "Assess activity.",
    operationalQuestion: "What changed?",
    areaOrRegion: "Baltic ports",
    timePeriodStart: null,
    timePeriodEnd: null,
    priority: "high",
    deadline: null,
    requiredOutputFormat: "Briefing note",
    knownContext: null,
    restrictionsOrCaveats: null,
    customerSuccessCriteria: "Support watch teams.",
    suggestedProjectName: null,
    suggestedAcgContext: null,
    missingInformation: [],
    confidence: 1,
  },
  isReadyForSubmission: true,
  suggestedProjectName: null,
  visibleProductMatches: [],
  releasedProductIds: [],
  collaborators: [],
  messages: [],
  attachments: [],
  agentRuns: [],
  timeline: [],
  createdAt: "2026-07-05T00:00:00Z",
  updatedAt: "2026-07-05T00:00:00Z",
};

export const rfiResultsFixture: RfiSearchResults = {
  ticketId: "ticket-1",
  ticketState: "RFI_MATCH_OFFERED",
  metrics: {
    runId: "run-1",
    query: "Regional Stability Brief Baltic ports assessment report",
    candidateCount: 1,
    offeredCount: 1,
    rejectedCount: 0,
    acceptedProductId: null,
    createdAt: "2026-07-05T00:01:00Z",
  },
  offers: [
    {
      productId: "product-1",
      title: "Regional Stability Brief",
      summary: "MOCK DATA ONLY assessment summary.",
      productType: "assessment_report",
      matchScore: 0.86,
      matchReasons: ["full-text:regional", "metadata:region"],
      classificationLevel: 2,
      releasability: ["MOCK"],
      region: "Baltic ports",
      timePeriodStart: null,
      timePeriodEnd: null,
      assetTypes: ["pdf"],
      offerableToUser: true,
      status: "offered",
      rejectionReason: null,
    },
  ],
};
