"""Synthetic capability team specs (MOCK DATA ONLY).

Each spec is ``(team_id, name, keywords, disciplines, regions, rank)`` where
keywords/disciplines/regions are space- or comma-separated strings and rank is
the team's relative importance weight (0..1) used by the recommendation
scorer. Team IDs are stable identifiers; do not rename them.
"""

RFA_TEAM_SPECS = (
    (
        "RFA-MARITIME",
        "Maritime Assessment Cell",
        "maritime port vessel shipping arctic baltic",
        "IMINT OSINT",
        "baltic, arctic, north atlantic",
        0.9,
    ),
    (
        "RFA-CYBER",
        "Cyber Threat Assessment Cell",
        "cyber malware intrusion network digital",
        "SIGINT OSINT",
        "global",
        0.85,
    ),
    (
        "RFA-REGIONAL",
        "Regional Stability Assessment Cell",
        "regional stability political crisis",
        "OSINT HUMINT",
        "eastern europe, middle east",
        0.8,
    ),
    (
        "RFA-GEO",
        "Geospatial Assessment Cell",
        "geospatial map imagery terrain border",
        "GEOINT IMINT",
        "global",
        0.8,
    ),
    (
        "RFA-ECON",
        "Economic Pressure Assessment Cell",
        "economic sanctions finance trade",
        "FININT OSINT",
        "global",
        0.6,
    ),
    (
        "RFA-INFRA",
        "Critical Infrastructure Assessment Cell",
        "infrastructure energy rail power",
        "GEOINT OSINT",
        "eastern europe",
        0.65,
    ),
    (
        "RFA-AIR",
        "Air And Space Assessment Cell",
        "aviation air missile satellite space",
        "IMINT SIGINT",
        "global",
        0.7,
    ),
    (
        "RFA-HEALTH",
        "Health Security Assessment Cell",
        "health medical disease biosecurity",
        "OSINT",
        "africa",
        0.5,
    ),
    (
        "RFA-SUPPLY",
        "Supply Chain Assessment Cell",
        "supply logistics port freight",
        "OSINT FININT",
        "global",
        0.55,
    ),
    (
        "RFA-COUNTER",
        "Counter-Proliferation Assessment Cell",
        "proliferation nuclear chemical",
        "MASINT TECHINT",
        "middle east",
        0.75,
    ),
    (
        "RFA-HUMAN",
        "Human Terrain Assessment Cell",
        "population humanitarian migration",
        "HUMINT OSINT",
        "africa, middle east",
        0.55,
    ),
    (
        "RFA-AFRICA",
        "African Regional Assessment Cell",
        "africa sahel regional political stability",
        "OSINT IMINT",
        "africa",
        0.6,
    ),
    (
        "RFA-GENERAL",
        "General Assessment Triage Cell",
        "assessment report brief analysis",
        "",
        "global",
        0.3,
    ),
)

CM_TEAM_SPECS = (
    (
        "CM-GEO-MARITIME",
        "Maritime Imagery Collection Cell",
        "imagery satellite port vessel maritime",
        "IMINT GEOINT",
        "baltic, arctic, north atlantic",
        0.9,
    ),
    (
        "CM-GEO-LAND",
        "Land GEOINT Tasking Cell",
        "geospatial terrain border facility map",
        "GEOINT IMINT",
        "eastern europe",
        0.8,
    ),
    (
        "CM-GEO-AFRICA",
        "African Imagery Exploitation Cell",
        "imagery satellite africa sahel overland",
        "IMINT GEOINT",
        "africa",
        0.7,
    ),
    (
        "CM-SIG-MARITIME",
        "Maritime Signals Collection Cell",
        "sigint signals vessel emitter radar",
        "SIGINT",
        "baltic, arctic, north atlantic",
        0.85,
    ),
    (
        "CM-SIG-EAST",
        "Eastern Europe Signals Cell",
        "sigint signals intercept emitter border",
        "SIGINT",
        "eastern europe, baltic, black sea",
        0.85,
    ),
    (
        "CM-SIG-CYBER",
        "Cyber Signals Collection Cell",
        "network beacon malware intrusion cyber",
        "SIGINT",
        "global",
        0.8,
    ),
    (
        "CM-OSINT-MEDIA",
        "Open Media Exploitation Cell",
        "media social public narrative osint",
        "OSINT",
        "global",
        0.6,
    ),
    (
        "CM-OSINT-COMMERCIAL",
        "Commercial Data Exploitation Cell",
        "commercial shipping trade registry",
        "OSINT FININT",
        "global",
        0.55,
    ),
    (
        "CM-HUMINT-LIAISON",
        "HUMINT Liaison Cell",
        "human source liaison access intent",
        "HUMINT",
        "middle east, eastern europe",
        0.7,
    ),
    (
        "CM-FININT",
        "Financial Intelligence Collection Cell",
        "finance sanctions payment ownership",
        "FININT",
        "global",
        0.6,
    ),
    (
        "CM-TECHINT",
        "Technical Intelligence Collection Cell",
        "technical equipment platform sensor",
        "TECHINT",
        "global",
        0.65,
    ),
    (
        "CM-MASINT",
        "Measurement And Signature Cell",
        "signature measurement radar acoustic",
        "MASINT",
        "global",
        0.6,
    ),
    (
        "CM-CYBER-SENSOR",
        "Cyber Sensor Coordination Cell",
        "sensor telemetry endpoint cyber",
        "SIGINT TECHINT",
        "global",
        0.7,
    ),
    (
        "CM-AVIATION",
        "Aviation Collection Coordination Cell",
        "air aviation flight runway aircraft",
        "IMINT SIGINT",
        "global",
        0.65,
    ),
    (
        "CM-SPACE",
        "Space Domain Collection Cell",
        "space satellite orbital launch",
        "IMINT MASINT",
        "global",
        0.75,
    ),
    (
        "CM-BORDER",
        "Border Monitoring Collection Cell",
        "border crossing checkpoint migration",
        "IMINT GEOINT",
        "eastern europe",
        0.6,
    ),
    (
        "CM-CLIMATE",
        "Environmental Collection Cell",
        "climate weather flood wildfire",
        "GEOINT OSINT",
        "global",
        0.4,
    ),
    (
        "CM-DARKWEB",
        "Dark Web Collection Cell",
        "darkweb forum illicit credential",
        "OSINT",
        "global",
        0.55,
    ),
    (
        "CM-LANGUAGE",
        "Language Exploitation Cell",
        "translation language document transcript",
        "OSINT HUMINT",
        "global",
        0.45,
    ),
    (
        "CM-UAS",
        "Uncrewed Systems Collection Cell",
        "drone uas overhead tactical",
        "IMINT",
        "eastern europe, middle east",
        0.7,
    ),
    (
        "CM-INFRA",
        "Infrastructure Monitoring Cell",
        "energy power pipeline rail infrastructure",
        "IMINT OSINT",
        "eastern europe",
        0.6,
    ),
    (
        "CM-SUPPLY",
        "Supply Chain Collection Cell",
        "supply logistics freight port cargo",
        "OSINT FININT",
        "global",
        0.55,
    ),
    (
        "CM-PATTERN",
        "Pattern Of Life Collection Cell",
        "pattern activity movement routine",
        "IMINT SIGINT",
        "global",
        0.65,
    ),
    (
        "CM-SANCTIONS",
        "Sanctions Evasion Collection Cell",
        "sanctions evasion vessel company",
        "FININT OSINT",
        "global",
        0.6,
    ),
    (
        "CM-MEDICAL",
        "Medical Collection Coordination Cell",
        "medical hospital disease health",
        "OSINT",
        "africa",
        0.45,
    ),
    (
        "CM-COUNTER",
        "Counter-Proliferation Collection Cell",
        "nuclear chemical missile proliferation",
        "MASINT TECHINT",
        "middle east",
        0.75,
    ),
    (
        "CM-GENERAL",
        "Collection Coordination Triage Cell",
        "collection collect tasking source",
        "",
        "global",
        0.3,
    ),
)
