from enum import StrEnum


class TicketState(StrEnum):
    DRAFT_INTAKE = "DRAFT_INTAKE"
    INFO_REQUIRED = "INFO_REQUIRED"
    RFI_SEARCHING = "RFI_SEARCHING"
    RFI_MATCH_OFFERED = "RFI_MATCH_OFFERED"
    ROUTE_ASSESSMENT = "ROUTE_ASSESSMENT"
    CLOSED_EXISTING_PRODUCT_ACCEPTED = "CLOSED_EXISTING_PRODUCT_ACCEPTED"
    CANCELLED = "CANCELLED"
