from enum import StrEnum


class TicketState(StrEnum):
    DRAFT_INTAKE = "DRAFT_INTAKE"
    INFO_REQUIRED = "INFO_REQUIRED"
    RFI_SEARCHING = "RFI_SEARCHING"
    RFI_MATCH_OFFERED = "RFI_MATCH_OFFERED"
    ROUTE_ASSESSMENT = "ROUTE_ASSESSMENT"
    RFA_MANAGER_REVIEW = "RFA_MANAGER_REVIEW"
    CM_MANAGER_REVIEW = "CM_MANAGER_REVIEW"
    ANALYST_ASSIGNMENT = "ANALYST_ASSIGNMENT"
    ANALYST_IN_PROGRESS = "ANALYST_IN_PROGRESS"
    QC_REVIEW = "QC_REVIEW"
    CLOSED_EXISTING_PRODUCT_ACCEPTED = "CLOSED_EXISTING_PRODUCT_ACCEPTED"
    CANCELLED = "CANCELLED"
