from enum import StrEnum


class Permission(StrEnum):
    AUTH_LOGIN = "auth:login"
    AUTH_LOGOUT = "auth:logout"
    USER_READ_SELF = "user:read_self"
    USER_UPDATE_SELF = "user:update_self"
    USER_CREATE = "user:create"
    USER_DISABLE = "user:disable"
    USER_ASSIGN_ROLE = "user:assign_role"
    ROLE_MANAGE = "role:manage"
    ACG_CREATE = "acg:create"
    ACG_UPDATE = "acg:update"
    ACG_ASSIGN_USER = "acg:assign_user"
    ACG_ASSIGN_PRODUCT = "acg:assign_product"
    ACG_VIEW = "acg:view"
    TICKET_CREATE = "ticket:create"
    TICKET_READ_OWN = "ticket:read_own"
    TICKET_READ_ALL = "ticket:read_all"
    TICKET_WRITE_ALL = "ticket:write_all"
    TICKET_ADD_INFORMATION = "ticket:add_information"
    TICKET_ADD_COMMENT = "ticket:add_comment"
    TICKET_TRANSITION = "ticket:transition"
    CHAT_USE = "chat:use"
    RFI_SEARCH = "rfi:search"
    RFI_OFFER_PRODUCT = "rfi:offer_product"
    RFI_ACCEPT_PRODUCT = "rfi:accept_product"
    RFI_REJECT_PRODUCT = "rfi:reject_product"
    JIOC_REVIEW = "jioc:review"
    RFA_REVIEW = "rfa:review"
    RFA_ASSIGN = "rfa:assign"
    RFA_ADD_PRODUCT = "rfa:add_product"
    COLLECTION_REVIEW = "collection:review"
    COLLECTION_ASSIGN = "collection:assign"
    COLLECTION_ADD_PRODUCT = "collection:add_product"
    ANALYST_WORK = "analyst:work"
    ANALYST_SUBMIT_PRODUCT = "analyst:submit_product"
    PRODUCT_APPROVE = "product:approve"
    TEAM_MANAGE = "team:manage"
    QC_REVIEW = "qc:review"
    QC_APPROVE = "qc:approve"
    QC_REJECT = "qc:reject"
    PRODUCT_CREATE_EXISTING = "product:create_existing"
    PRODUCT_CREATE_FROM_QC = "product:create_from_qc"
    PRODUCT_READ = "product:read"
    PRODUCT_READ_RESTRICTED = "product:read_restricted"
    PRODUCT_UPDATE_METADATA = "product:update_metadata"
    PRODUCT_MANAGE_ASSETS = "product:manage_assets"
    PRODUCT_PUBLISH = "product:publish"
    PRODUCT_ARCHIVE = "product:archive"
    PRODUCT_SEARCH = "product:search"
    STORE_BROWSE_ALL = "store:browse_all"
    PRODUCT_DOWNLOAD = "product:download"
    PRODUCT_DISSEMINATE = "product:disseminate"
    FEEDBACK_CREATE = "feedback:create"
    FEEDBACK_READ = "feedback:read"
    ANALYTICS_VIEW_OWN = "analytics:view_own"
    ANALYTICS_VIEW_TEAM = "analytics:view_team"
    ANALYTICS_VIEW_GLOBAL = "analytics:view_global"
    AUDIT_READ = "audit:read"
    SYSTEM_CONFIGURE = "system:configure"


ALL_PERMISSIONS = frozenset(Permission)
