name: Terraform IaC

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/environments/dev
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.10.5"
          terraform_wrapper: false
      - name: Terraform fmt
        run: terraform fmt -check -recursive ../..
      - name: Terraform init
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate
